[tool.poetry]
name = "ml-project-demo"
version = "0.1.0"
description = "Demo ml project"
authors = ["Golgovskiy"]
readme = "README.md"
repository = "https://github.com/Golgovskiy/ml-project-demo"
keywords = ["demo"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
