on:
  push:
    branches: 
      - master
#   pull_request:
#     branches: 
#       - main

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.8,3.9,3.10]

    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Run nox
      run: |
        poetry run nox
